name: Operating_system

on:
  workflow_dispatch:

jobs:
  mac:
    runs-on: macos-latest
    steps:
      - name: mac version
        run: sw_vers -productVersion
  windows:
    runs-on: windows-latest
    steps:
      - name: windows version
        run: Get-ComputerInfo | select OsVersion
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: ubutu version
        run: lsb_release -d
